### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by keszybz** [nsdf/nsdf#42]
Any plans?

**Comment by subhacom** [comment]
I thought I had checked it against Python3. Will take a look this weekend. Should be rather easy.
Also, I wanted to check if it is OK to put you name in contributors list?

**Comment by keszybz** [comment]
git grep shows a lot of print statements... It is in mostly in benchmark and examples, but also in tests.

>  I wanted to check if it is OK to put you name in contributors list?

I don't feel that I have made any significant contributions ;), but I have no objections apart from that.

**Comment by subhacom** [comment]
Now there is a py3k branch. Only issue is h5py 2.2.1 for Python3 had some issues with string/unicode. Will check with the latest version.

**Comment by subhacom** [comment]
Fixed in https://github.com/nsdf/nsdf/pull/49
